### ISSUE TITLE
Using Record Offset in Query

### ISSUE THREAD

**Issue by tfoshag** [hamid-vakilzadeh/python-xbrl-us#6]
Hello, 
I am using this module via Spyder with Python 3.8 on a Windows machine. 

I am trying to run an API query that includes a record offset but it doesn't appear that the API query incorporates the record offset in the output results as I get the same resulting dataframe regardless of whether the offset parameter is specified in the query or not. It doesn't appear that the offset condition is being used in the query when I use the print query command so curious if I am inputting the offset parameter incorrectly or if there is something in the source code that is not building the offset parameter into the API query. 

Thanks.      

`Test2 = xbrl.query(
    method='report search',
    parameters={
        "report.document-type": ['10-K'],
    },
    fields=[
        'report.accession',
        'report.entity-name',
        'report.filer-category',
        'report.period-end',
        'report.filing-date',
        'report.period-index',
        'report.sec-url',
        'report.sic-code',
        'report.state-of-incorporation',
        'report.filing-date'
    ],
    sort={"report.filing-date": "DESC"},
    limit=500,
    timeout=60,
    print_query=True,
    offset=489,
    as_dataframe=True
)`

**Comment by hamid-vakilzadeh** [comment]
Hello @tfoshag ,
The offset variable is not controlled by the user. Instead the program will determine whether the use of offset is needed or not. For example, if your account limit is 5000 and you are requesting 500 (as shown in your example) you will receive 500 observations. However if you select a 10000 limit, the program will automatically take care of the offset variable and would iterate twice (because 10000 is twice as big as your account limit. 

I hope this answers your question. If I have not understood your question correctly please let me know.

**Comment by tfoshag** [comment]
Thank you so much for the quick response @hamid-vakilzadeh. This makes total sense and I verified the issue was 100% user error in not understanding how the offset was working in the program. 

Thank you again for your help and for developing this module.

**Comment by hamid-vakilzadeh** [comment]
I am glad the issue was resolved. 😊  Thank you for your kind words.

**Comment by tfoshag** [comment]
@hamid-vakilzadeh  Above solution works for the 0.0.41 version of the module but I recently upgraded to the 0.0.42 version of the module on a new computer. When I run the code and there are 9,081 instances with a limit field of 37,500 in my query the resulting dataframe in the 0.0.42 module only outputs 5,000 observations instead of 9,081 like it does in the 0.0.41 version. Reverting back to running 0.0.41 but just wanted to let you know. 

Thanks and let me know if any other details here would be helpful.

**Comment by hamid-vakilzadeh** [comment]
@tfoshag  thank your for letting me know. I will look into this issue

**Comment by hamid-vakilzadeh** [comment]
Hi Travis,

After looking into the code, I discovered what the problem was. :) 
I am very happy that you report all these issues.

This issue was resolved in version 0.0.43.
I will close this issue but feel free to reopen it if the issue persists.

**Comment by tfoshag** [comment]
Thanks Hamid. I updated my module version to 0.0.43 and it performed perfectly in pulling all the record requests if I set the limit to exceed my XBRL US account limit. Thank you so much for updating that. Really appreciate all your work on this module. 

I did also try to see if issue #7 was resolved in version 0.0.43 but unfortunately the issue documented therein still persists in this version of the module. Will add a note to that issue thread that the issue appears to persist in this version as well. 

Thanks again for everything. I am so appreciative!
--Travis
